# Generated by Django 4.2.3 on 2023-07-04 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposts',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
