# Generated by Django 4.2.3 on 2023-07-04 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogsApi', '0002_blogposts_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogposts',
            name='time_created',
        ),
        migrations.RemoveField(
            model_name='blogposts',
            name='time_updated',
        ),
    ]
