# Generated by Django 4.2.3 on 2023-07-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsApi', '0003_remove_blogposts_time_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='category',
            field=models.CharField(choices=[('world', 'World'), ('environment', 'Environment'), ('technology', 'Technology'), ('culture', 'Culture'), ('business', 'Business'), ('politics', 'Politics'), ('science', 'Science'), ('health', 'Health'), ('travel', 'Travel')], default='world', max_length=50),
        ),
    ]
