# Generated by Django 4.2.3 on 2023-09-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsApi', '0004_alter_blogposts_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposts',
            name='latest',
            field=models.BooleanField(default=False),
        ),
    ]
